import { Inter } from 'next/font/google';
import "../app/globals.css";
import { storyblokInit, apiPlugin } from "@storyblok/react/rsc";
import type { Metadata } from "next";
import StoryblokProvider from 'compnents/storyblokProvider';
import { ISbStoriesParams, getStoryblokApi } from "@storyblok/react/rsc";

const inter = Inter({ subsets: ['latin'] });
export const metadata: Metadata = {
  title: "Contact - Next",
  description: "Generated by create next app",
};

export async function fetchHeaderData() {
  let sbParams: ISbStoriesParams = {
    version: "draft",
    cv: new Date().getTime(),
  };
  const storyblokApi = getStoryblokApi();
  return storyblokApi.get(`cdn/stories/config`, sbParams);
}

storyblokInit({
  accessToken: "h3hqQmXX80zfgKL7rRehdAtt",
  use: [apiPlugin],
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { data } = await fetchHeaderData();
  return (
    <StoryblokProvider>
      <html lang="en" data-bs-theme="light">
        <body style={{ paddingTop: 165 + "px" }}>
          <main className="page-wrapper">
            {children}
          </main>
        </body>
      </html>
    </StoryblokProvider>
  )
}